language: emacs-lisp

env:
  matrix:
    - EVMVERSION=emacs-25.3-travis
    - EVMVERSION=emacs-26.1-travis
    - EVMVERSION=emacs-27.1-travis-linux-xenial
    - EVMVERSION=emacs-git-snapshot-travis

before_install:
  - source travis-evm-cask.sh
install:
  # Install our packages
  - make compile
script:
  # Run the unit tests
  - make test