language: emacs-lisp

sudo: required
dist: trusty

cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
# Allow Emacs snapshot builds to fail and don’t wait for these as they can take
# a looooong time
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=25.3
    - env: EMACS_VERSION=snapshot
env:
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=26.2
  - EMACS_VERSION=26.3
  - EMACS_VERSION=27.1
  - EMACS_VERSION=snapshot
before_install:
  # Configure $PATH: Executables are installed to $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - sudo apt-get install -y gnutls-bin
  - gnutls-cli --version
  # Download the makefile to emacs-travis.mk
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
  # Install Texinfo, if you need to build info manuals for your project
  - make -f emacs-travis.mk install_texinfo
install:
  # Install your dependencies
  - emacs --batch --eval "(pp system-configuration-features)"
  - emacs --batch --eval "(pp (gnutls-available-p))"
  - cask install
script:
  # Run your tests
  - make build
  - make test
